#!/bin/bash
ONE_GIG=1073741824
WEEK_COUNT=168
python2.7 /usr/share/clearwater/bin/log_cleanup.py /var/log/homestead --prefix homestead_ --maxsize $ONE_GIG --count $WEEK_COUNT
python2.7 /usr/share/clearwater/bin/log_cleanup.py /var/log/homestead --prefix access_ --maxsize $ONE_GIG --count $WEEK_COUNT
python2.7 /usr/share/clearwater/bin/log_cleanup.py /var/lib/cassandra --suffix hprof --count 2
