#!/bin/bash
ONE_GIG=1073741824
python2.7 /usr/share/clearwater/bin/log_cleanup.py /var/log/homestead --prefix homestead_ --max_size $ONE_GIG
python2.7 /usr/share/clearwater/bin/log_cleanup.py /var/log/homestead --prefix access_ --max_size $ONE_GIG
python2.7 /usr/share/clearwater/bin/log_cleanup.py /var/lib/cassandra --suffix hprof --count 2
