#!/bin/bash
ONE_GIG=1073741824
python2.7 /usr/share/clearwater/bin/log_cleanup.py /var/log/homestead homestead_ $ONE_GIG
python2.7 /usr/share/clearwater/bin/log_cleanup.py /var/log/homestead access_ $ONE_GIG
python2.7 /usr/share/clearwater/bin/log_cleanup_count.py /var/lib/cassandra 2 --suffix hprof
